#!/usr/bin/env bash
# install.sh — Symlink bin/* into ~/.local/bin/ so commands run from anywhere.
# Works on macOS and Linux. Safe to re-run. Backs up any conflicting existing files.
# Windows users: run  .\install.ps1  in PowerShell instead.

set -euo pipefail
PROJ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_BIN="$HOME/.local/bin"
mkdir -p "$LOCAL_BIN"

OS="$(uname -s 2>/dev/null || echo unknown)"
echo "Platform: $OS"
echo "Project:  $PROJ_DIR"
echo "Target:   $LOCAL_BIN"
case "$OS" in
  Linux) echo "Note: gemma / mlx-serve-* are Apple-Silicon (MLX) tools — on Linux use an Ollama model (THMES_MODEL=ol:<tag>)." ;;
esac
echo ""

backup() {
  local target="$1"
  if [ -L "$target" ]; then
    rm "$target"                                  # old symlink → replace
  elif [ -f "$target" ] && grep -q 'thmes-installer-wrapper' "$target" 2>/dev/null; then
    rm "$target"                                  # our own generated wrapper → regenerate (idempotent)
  elif [ -e "$target" ]; then
    local bak="${target}.bak-$(date +%Y%m%d-%H%M%S)"
    mv "$target" "$bak"
    echo "  ↪ backed up existing $target → $bak"
  fi
}

# Resolve the best available Python interpreter for wrapper scripts.
# Priority: shebang path → ~/.mlx-env/bin/python → python3
_shebang_python() {
  local src="$1"
  head -1 "$src" | sed 's/^#![[:space:]]*//' | tr ' ' '\n' | grep '/' | tail -1
}

install_script() {
  local src="$1"
  local dst="$2"
  local name
  name="$(basename "$dst")"

  [ -f "$src" ] || return 0
  backup "$dst"

  local shebang_py
  shebang_py="$(_shebang_python "$src")"

  if [ -x "$shebang_py" ]; then
    # Shebang Python exists on this machine — simple symlink
    ln -s "$src" "$dst"
    echo "  ✓ $name  →  $src"
  else
    # Shebang Python not found — create a thin wrapper using local Python
    # Fallback priority: thmes venv → legacy mlx venv → system python3
    local py=""
    for candidate in \
        "${HOME}/.thmes-env/bin/python" \
        "${HOME}/.mlx-env/bin/python"; do
      [ -x "$candidate" ] && py="$candidate" && break
    done
    [ -n "$py" ] || py="$(command -v python3 2>/dev/null || echo python3)"
    cat > "$dst" << WRAPPER
#!/usr/bin/env bash
# thmes-installer-wrapper (auto-generated by install.sh — safe to delete/regenerate)
exec "$py" "$src" "\$@"
WRAPPER
    chmod +x "$dst"
    echo "  ✓ $name  →  $src  (wrapper: $py)"
  fi
}

# This is the DEV (private) checkout — it installs every command under a `dev-`
# prefix (dev-thmes, dev-thmes-pro, …) so it coexists with a public `thmes`
# install on the same machine.
SCRIPTS="thmes thmes-pro thmes-daemon thmes-web gemma hermes-use \
mlx-serve-gemma mlx-serve-qwen mlx-serve-qwen3"
for script in $SCRIPTS; do
  install_script "$PROJ_DIR/bin/$script" "$LOCAL_BIN/dev-$script"
done

# Free any UN-prefixed command left by a PREVIOUS install of THIS repo, so it no
# longer shadows a public `thmes` install (only removes links that point here).
for script in $SCRIPTS; do
  old="$LOCAL_BIN/$script"
  if { [ -L "$old" ] && [ "$(readlink "$old")" = "$PROJ_DIR/bin/$script" ]; } \
     || { [ -f "$old" ] && grep -q "$PROJ_DIR/bin/$script" "$old" 2>/dev/null; }; then
    rm "$old"; echo "  ↪ removed old un-prefixed '$script' (now 'dev-$script')"
  fi
done

# Remove stale symlinks from the pre-rename layout (gemma-pro/gemma-daemon)
for old in gemma-pro gemma-daemon; do
  [ -L "$LOCAL_BIN/$old" ] && rm "$LOCAL_BIN/$old" && echo "  ↪ removed stale $old symlink"
done

# ── Web UI config: ensure `websockets` so `dev-thmes-web` works on first run ──────
# thmes-web auto-installs it on demand too, but doing it here makes the first launch
# instant. Pick the same Python the wrappers use (thmes venv → mlx venv → python3).
echo ""
WEB_PY=""
for candidate in "${HOME}/.thmes-env/bin/python" "${HOME}/.mlx-env/bin/python"; do
  [ -x "$candidate" ] && WEB_PY="$candidate" && break
done
[ -n "$WEB_PY" ] || WEB_PY="$(command -v python3 2>/dev/null || true)"
if [ -n "$WEB_PY" ]; then
  if "$WEB_PY" -c "import websockets" 2>/dev/null; then
    echo "  ✓ web UI: 'websockets' present in $WEB_PY"
  else
    echo "  → web UI: installing 'websockets' into $WEB_PY …"
    if "$WEB_PY" -m pip install --quiet websockets 2>/dev/null; then
      echo "  ✓ web UI ready — run 'dev-thmes-web', open http://localhost:8765"
    else
      echo "  ⚠ web UI: websockets install failed — 'dev-thmes-web' will retry on first run"
    fi
  fi
else
  echo "  ⚠ web UI: no Python found to install 'websockets'"
fi

echo ""
echo "✓ Installation complete."
echo ""
echo "Make sure $LOCAL_BIN is in your PATH:"
echo "  echo \$PATH | tr ':' '\\n' | grep -q '$LOCAL_BIN' && echo 'OK' || echo 'MISSING'"
echo ""
echo "If missing, add to ~/.zshrc:"
echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
echo ""
echo "Try:  dev-thmes        (this dev build; the public release installs as 'thmes')"
echo "      dev-thmes-web    (browser terminal → http://localhost:8765)"
