#!/usr/bin/env python3
"""THMES Web Terminal — run the thmes CLI in a browser over a PTY + WebSocket.

The browser (xterm.js, index.html) connects over WebSocket; this server spawns the
real `thmes` REPL inside a pseudo-terminal and bridges bytes both ways. Everything
runs locally on this machine — the terminal session never leaves it.

    python3 server.py            # or:  thmes-web
    open http://localhost:8765

Config via env:
    THMES_WEB_HTTP_PORT   static-page port            (default 8765)
    THMES_WEB_WS_PORT     PTY/websocket bridge port    (default 8766)
    THMES_CMD             command that launches the CLI (default: resolve `thmes`)
    THMES_MODEL           forwarded to the CLI          (e.g. ol:gemma4:e4b)

Requires the `websockets` package:  pip install websockets

Origin: the frontend (index.html) was generated by thmes itself in relay mode
(cloud=brain, this machine=hands); this backend was then productionised for the repo
(portable paths + a single-reader PTY bridge). See docs/CODEMAP.md §10.
"""
from __future__ import annotations
import asyncio
import http.server
import os
import pty
import shlex
import shutil
import signal
import socketserver
import subprocess
import sys
import threading
from pathlib import Path

HERE = Path(__file__).resolve().parent
HTTP_PORT = int(os.environ.get("THMES_WEB_HTTP_PORT", "8765"))
WS_PORT = int(os.environ.get("THMES_WEB_WS_PORT", "8766"))

try:
    import websockets
except ImportError:
    sys.exit("THMES Web Terminal needs the 'websockets' package:\n  pip install websockets")


def _thmes_cmd() -> list:
    """Resolve the command that launches the thmes REPL, portably (this repo is
    synced across machines, so nothing is hardcoded):
      1. $THMES_CMD (shell-split) — set this if the shebang python isn't on this host
      2. `thmes` on PATH (installed symlink → runs via its own shebang)
      3. <repo>/bin/thmes relative to this file
    """
    env_cmd = os.environ.get("THMES_CMD")
    if env_cmd:
        return shlex.split(env_cmd)
    on_path = shutil.which("thmes")
    if on_path:
        return [on_path]
    local = HERE.parent / "bin" / "thmes"
    return [str(local)] if local.exists() else ["thmes"]


class _Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *a, **k):
        super().__init__(*a, directory=str(HERE), **k)

    def log_message(self, *a):   # keep the console quiet
        pass


def _serve_http():
    with socketserver.TCPServer(("", HTTP_PORT), _Handler) as httpd:
        httpd.serve_forever()


async def _bridge(websocket):
    """One browser connection ⇄ one thmes process in a PTY."""
    cmd = _thmes_cmd()
    env = dict(os.environ)
    env.setdefault("TERM", "xterm-256color")
    master, slave = pty.openpty()
    proc = subprocess.Popen(cmd, stdin=slave, stdout=slave, stderr=slave,
                            env=env, preexec_fn=os.setsid, close_fds=True)
    os.close(slave)
    os.set_blocking(master, False)
    loop = asyncio.get_running_loop()

    # Single non-blocking reader registered with the event loop — fires once per
    # readable event, reads what's there, ships it to the browser. (No inner polling
    # loop, so no duplicate reader tasks.)
    def _on_readable():
        try:
            data = os.read(master, 65536)
        except (BlockingIOError, InterruptedError):
            return
        except OSError:
            data = b""
        if not data:                                  # EOF → child exited
            loop.remove_reader(master)
            asyncio.create_task(websocket.close())
            return
        asyncio.create_task(websocket.send(data.decode("utf-8", "replace")))

    loop.add_reader(master, _on_readable)
    print(f"[thmes-web] client connected → {' '.join(cmd)} (pid {proc.pid})")
    try:
        async for msg in websocket:                   # browser keystrokes → PTY
            if msg:
                os.write(master, msg.encode("utf-8") if isinstance(msg, str) else msg)
    except websockets.ConnectionClosed:
        pass
    finally:
        try:
            loop.remove_reader(master)
        except Exception:
            pass
        try:
            os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
        except Exception:
            proc.terminate()
        try:
            os.close(master)
        except Exception:
            pass
        print(f"[thmes-web] client disconnected (pid {proc.pid} terminated)")


async def main():
    threading.Thread(target=_serve_http, daemon=True).start()
    async with websockets.serve(_bridge, "", WS_PORT):
        print(f"[thmes-web] spawns : {' '.join(_thmes_cmd())}")
        print(f"[thmes-web] bridge : ws://localhost:{WS_PORT}")
        print(f"[thmes-web] open   : http://localhost:{HTTP_PORT}")
        await asyncio.Future()   # run forever


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n[thmes-web] bye")
